# Generated by Django 5.0.2 on 2024-02-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('date_published', models.DateField()),
                ('source', models.CharField(max_length=500)),
                ('original_text_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('original_text', models.TextField()),
                ('difficulty_level_easy_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('difficulty_level_easy_text', models.TextField()),
                ('difficulty_level_medium_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('difficulty_level_medium_text', models.TextField()),
                ('difficulty_level_hard_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('difficulty_level_hard_text', models.TextField()),
            ],
        ),
    ]
