# Generated by Django 5.0.2 on 2024-02-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherWorm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='difficulty_level_easy_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='difficulty_level_hard_id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='difficulty_level_medium_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_published',
            field=models.CharField(max_length=500),
        ),
    ]
