# Generated by Django 5.0.2 on 2024-02-18 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherWorm', '0004_remove_article_difficulty_level_easy_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('TF', 'TF'), ('FRQ', 'FRQ')], max_length=50)),
                ('mcq_incorrect_choice_1', models.TextField(null=True)),
                ('mcq_incorrect_choice_2', models.TextField(null=True)),
                ('mcq_incorrect_choice_3', models.TextField(null=True)),
                ('mcq_correct_choice', models.TextField(null=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherWorm.article')),
            ],
        ),
    ]
